market_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: airflow
      password: airflow # or your actual password
      port: 5432
      dbname: airflow
      schema: public
      threads: 1
      connect_timeout: 10
