version: "3.8"

x-airflow-env: &airflow_env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/raw:/data/raw

  airflow-init:
    build: ./docker/airflow
    depends_on: [postgres]
    environment: *airflow_env
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-webserver:
    build: ./docker/airflow
    depends_on: [airflow-init]
    environment: *airflow_env
    command: webserver
    ports: ["8080:8080"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/dbt
      - ./data:/data

  airflow-scheduler:
    build: ./docker/airflow
    depends_on: [airflow-init]
    environment: *airflow_env
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/dbt
      - ./data:/data

  api:
    build: ./api
    environment:
      DATABASE_URL: postgresql://airflow:airflow@postgres:5432/airflow
    ports: ["8000:8000"]
    depends_on: [postgres]

  metabase:
    image: metabase/metabase:latest
    ports: ["3000:3000"]
    depends_on: [postgres]
    environment:
      MB_DB_FILE: /metabase.db
    volumes:
      - metabase:/metabase-data

volumes:
  pgdata: {}
  metabase: {}
